### ISSUE TITLE
Counter-Punch Not Loading from Hero Builder

### ISSUE THREAD

**Issue by Improvidence** [funkymonkeymonk/tts-marvel-champions-automated#2]
When loading up the Captain America Stun Lock 2.0 deck, the deck ended up being 38 cards.  My friend and I both experienced the issue.

https://marvelcdb.com/decklist/view/482/stun-lock-2-0-captain-america-protection-1.0

The missing cards were two copies of Counter-Punch.  I tried loading up another deck that included the card, and again they failed to load.

When looking at the card pool, I see the card is listed as "Counter-punch" with the lower case on the P, but it's upper case on MarvelCDB.  I wonder if that's why it's not loading?

Thanks for the great mod!  It's made setting up games so much easier.

**Comment by funkymonkeymonk** [comment]
Thanks for filing a bug report. I'll take a look right now.

**Comment by funkymonkeymonk** [comment]
You were spot on. There was a typo in the name which was causing the issue. I just uploaded the workshop version to correct.
