### ISSUE TITLE
Error when importing a public deck from marvelCDB

### ISSUE THREAD

**Issue by dassuave** [funkymonkeymonk/tts-marvel-champions-automated#20]
Error when importing a public deck from marvelCDB, "Error in Script (Marvel Champions Helper - 330ff1) function <buildHeroDeckClicked>:chunk_3:(636,26-107)>: attempt to concatenate a nil value"

![image](https://user-images.githubusercontent.com/28657290/88472031-10dc3400-cec4-11ea-8eeb-73e9761e1f13.png)

Table size set to 1,
Deck ID: 1771 (should link to https://marvelcdb.com/decklist/view/1771)

Sequence of actions: 
In TTS Clicked the Create button
Chose Single-Player
Clicked the Workshop button
Clicked Marvel Champions Automated
Clicked Load
Waited for the Loading Complete message
Clicked the red deck to open the Marvel UI
Clicked the deck builder button
Pasted in the string '1771'
Clicked the button to toggle to public deck
Clicked the button to Build Hero Deck
Error occurs

**Comment by funkymonkeymonk** [comment]
Should be all good. I already pushed an update to resolve.
