### ISSUE TITLE
Different sized encounter cards

### ISSUE THREAD

**Issue by 2sith4u** [funkymonkeymonk/tts-marvel-champions-automated#3]
When running script to create encounter deck the Villain and Environment cards were of different sizes and couldn't be shuffled together into one deck. The Villain ones just sat on top of the Environment ones. 

I tried one a couple Villains and environments and found same thing,

**Comment by funkymonkeymonk** [comment]
Thanks for the bug report. It broke with the latest update to TTS. For right now you can drag select the pile and hit G to group them but it's certainly not an ideal solution. 
Were you able to confirm the issue is the card sizes? If you resize the card stacks and put them back in the bag does the automation work?

**Comment by 2sith4u** [comment]
Thanks for replying :)
I am new to TTS but will try to check it out. Will reply back either way if
I can test.
Great mod otherwise,
Greg

**Comment by funkymonkeymonk** [comment]
Happy to hop into a game with you and pair on testing it. If your on the Deckcelcior discord hit me up there. I'm FunkyMonkeyMonk.

**Comment by 2sith4u** [comment]
Awesome!
Do you have a link to the server?

**Comment by funkymonkeymonk** [comment]
[Deckcelsior Discord](https://discord.gg/dXWBhSx)

**Comment by 2sith4u** [comment]
Hey,

Confirmed if you scale up the villain cards three times they will fit
together automatically but I haven't been able to get them back into the
bags and build from the script

Greg

**Comment by funkymonkeymonk** [comment]
Thanks for confirming the fix . If you'd like to be a contributor, I'm happy to show you how tomorrow on over discord. Else I'll take care of it tomorrow afternoon.

**Comment by 2sith4u** [comment]
Hey,

Happy to work on it with you. Haven't made a mod myself yet but would like
to learn whatever I can.

Will try and catch you on discord sometime.
Greg

**Comment by funkymonkeymonk** [comment]
Thanks for fixing @2sith4u It's been uploaded.
